# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('TH', 'Temperature and Humidity'), ('LI', 'Light')], max_length=64)),
                ('model', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17)),
                ('address', models.GenericIPAddressField(protocol='IPv4')),
                ('netmask', models.GenericIPAddressField(protocol='IPv4')),
                ('gateway', models.GenericIPAddressField(protocol='IPv4')),
                ('location', models.CharField(max_length=128)),
                ('poll_rate', models.IntegerField(default=60)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Device')),
            ],
            options={
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('F', 'F'), ('C', 'C'), ('INT', 'Integer'), ('FLT', 'Float')], max_length=16)),
                ('measurement', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
